// <auto-generated />
namespace PetCityApi1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addRoomTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addRoomTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202211210816157_addRoomTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
